apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boilerplate

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - mongodb.yaml
  - kafka.yaml
  - jaeger.yaml
  - prometheus.yaml
  - user-service.yaml
  - api-gateway.yaml
  - web-app.yaml

commonLabels:
  app.kubernetes.io/part-of: boilerplate
  app.kubernetes.io/managed-by: kustomize
